### ISSUE TITLE
Support for global and project snippets

### ISSUE THREAD

**Issue by jabacchetta** [inu1255/vscode-easy-snippet#1]
It'd be great to be able to see existing global snippet files and project-specific snippet files in the snippet view manager.

Optionally, there could also be a second command: "Create global snippet by select", that would allow you to select which existing global snippet file that the snippet should be placed in. Preferably, the snippet would get the `scope` property that the global snippets JSON schema allows for, with the auto-detected language already added. For example, if the select was done in a JavaScript file, the JavaScript scope would be added. Then users could manually add "TypeScript" to the scope so that the snippet works in both JavaScript and TypeScript.

Thanks for the great extension, by the way!

**Comment by zbahadir** [comment]
Hello,
Very useful expansion. It would be nice to edit project and general sinippet files. 
If I have time, I'il try to add it myself.

Thank you for this extension.

**Comment by inu1255** [comment]
Sorry to reply so late, but this feature is already supported.
