### ISSUE TITLE
Group addition problem

### ISSUE THREAD

**Issue by zbahadir** [inu1255/vscode-easy-snippet#14]
Hello, 

A new problem has occurred. The same problem exists in both the stable version and the Insider version.

Cannot read property 'document' of undefined
![easy_snippet](https://user-images.githubusercontent.com/3078225/78462394-28f03380-76da-11ea-9242-6f8c8187e52f.png)

**Comment by inu1255** [comment]
This problem occurs when no active file. 
Now it's been fixed.
