### ISSUE TITLE
Refresh button fault

### ISSUE THREAD

**Issue by TechJA** [inu1255/vscode-easy-snippet#16]
HI,
congrats for your vscode extension

I can't refresh the easy-snippet list after add or delete a snippet. The refresh button doesn't work.

I'm using codium 1.44.0 and Linux Mint 19.3

**Comment by demidenko** [comment]
panel refreshes only after resave of json file with snippets

**Comment by inu1255** [comment]
I'm sorry it took so long to reply, but this question should no longer exist, right?
