### ISSUE TITLE
Support Workspace/Project snippets

### ISSUE THREAD

**Issue by pedro-mass** [inu1255/vscode-easy-snippet#20]
doc: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_project-snippet-scope

I'd like to be able to create & modify project snippets, but can't seem to find them with this extension.

Is this doable?

So far I like this extension the best b/c it allows for easy viewing and editing of snippets. If it's not too troubling, maybe I can make contribution.

**Comment by barraIhsan** [comment]
Support!

**Comment by LangLangBart** [comment]
Try `Snippets Manager`
<img src="https://ttm.sh/ia1.png" width="600">

Related to issue #1

**Comment by inu1255** [comment]
This feature is supported after 0.7.0
