### ISSUE TITLE
Renaming snippet names

### ISSUE THREAD

**Issue by TarjinderSingh** [inu1255/vscode-easy-snippet#25]
After creating a snippet, we can edit the prefix, description, and body, but cannot rename the snippet name itself. Would it be possible to do it from the menu? Thanks!

**Comment by cmarabate** [comment]
I also think this is needed.

**Comment by inu1255** [comment]
Now you can rename it through the icon on the snippet
![image](https://github.com/inu1255/vscode-easy-snippet/assets/5772409/24c72f44-5b79-4ed3-b4b7-c68f958b521a)
