### ISSUE TITLE
Error when trying to create a snippet

### ISSUE THREAD

**Issue by lambda0xff** [inu1255/vscode-easy-snippet#28]
Error running command snippetExplorer.addSnippet: Cannot read property 'document' of undefined. This is likely caused by the extension that contributes snippetExplorer.addSnippet.

vscode:
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:23:52.277Z (3 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by vmcgonigle** [comment]
For anyone coming here for the same issue, it seems to automatically resolve after about a half hour. At least on my machine.
