### ISSUE TITLE
Error when adding a new "global" snippet using .code-snippets

### ISSUE THREAD

**Issue by reggi** [inu1255/vscode-easy-snippet#29]
Love this tool! When using File -> User snippets and create a new global snippet VSCode will use the new `.code-snippet` extension for the file, when this file is in `.../Code/User/snippets` it causes issues with this extension. I'd love support for global snippets, as well as for this bug to be fixed.

**Comment by Remodor** [comment]
Just noticed the same problem with global snippets. +1 for the suggestion!

**Comment by kedniko** [comment]
Any news on this? I'd love support for global snippets too!

**Comment by inu1255** [comment]
Sorry to reply so late, but this feature is already supported.
