### ISSUE TITLE
Running the contributed command: 'snippetExplorer.addSnippet' failed.

### ISSUE THREAD

**Issue by Jackiexiao** [inu1255/vscode-easy-snippet#35]
I try to bind hotkey for addSnippet, but it failed
![image](https://user-images.githubusercontent.com/18050469/128591684-2a858201-efa2-4908-9382-09f1cd59bfb9.png)

![image](https://user-images.githubusercontent.com/18050469/128591691-eb6ac5fc-5d9e-4b31-808d-d6fc4e5524b2.png)

**Comment by inu1255** [comment]
I'm sorry it took so long to reply, this issue is fixed.
