### ISSUE TITLE
Insert Snippet into current document?

### ISSUE THREAD

**Issue by WebSpectrum** [inu1255/vscode-easy-snippet#38]
Am I right in saying there is no way to insert a select snippet into the current working document? I have to remeber trigger words for snippets and sometimes I forget

**Comment by inu1255** [comment]
this just is an editor for vscode build-in snippets feature. 
maybe you can use build-in `Insert Snippets` command to search and insert snippet
![image](https://github.com/inu1255/vscode-easy-snippet/assets/5772409/3af5b931-3d76-4c8a-8a1c-420418515b40)
