### ISSUE TITLE
Not working with VSCode 1.75 code profiles

### ISSUE THREAD

**Issue by mathiasandresen** [inu1255/vscode-easy-snippet#42]
When I have activated a configuration profile, the extension still manages user snippets, which does not seem to affect profile snippets

**Comment by joaquimnetocel** [comment]
Same problem here! Not working with profiles.

**Comment by inu1255** [comment]
now you can set `Snippets Path` on other profile
![image](https://github.com/inu1255/vscode-easy-snippet/assets/5772409/06fdc673-6be2-4872-8ce5-ec284e0cdc35)
