### ISSUE TITLE
Cursor Placement

### ISSUE THREAD

**Issue by tjrush** [inu1255/vscode-easy-snippet#43]
Type: <b>Performance Issue</b>

When creating a snippet, is there a way to indicate where the cursor should be placed when the snippet is loaded?

Extension version: 0.6.3
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 x 3504)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.87GB (24.88GB free)|
|Process Argv|--crash-reporter-id d9b7f456-efae-405c-960b-0398dd06ee26|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    92	  6800	code main
    0	    28	  2148	   crashpad-handler
    0	   127	  3324	   extension-host
    0	    72	 12708	     "C:\Users\Tom\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Tom\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=3324
    0	    85	  3572	   issue-reporter
    0	    40	 13048	   utility-network-service
    0	    94	 14928	   gpu-process
    0	   102	 16032	   shared-process
    0	    77	  3452	     fileWatcher
    0	    74	 15916	     ptyHost
    0	   134	 22348	   window (CAA_Mini - Visual Studio Code [Administrator])
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (CAA_Mini - Visual Studio Code [Administrator])
|    Folder (CAA_Mini): 42 files
|      File types: php(8) css(6) ttf(4) woff2(4) jpg(3) txt(2) properties(2)
|                  xml(2) gif(1) ico(1)
|      Conf files:;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30660299
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30662992
f6dab269:30613381
pythonsymbol12:30657548
a9j8j154:30646983
vsctsb:30662444
vscodeenable:30660116

```

</details>

**Comment by therealsujitk** [comment]
You can use `$0`, `$1`, `$2` etc. to specify where the cursor should be placed after the snippet loads. ~ [VS Code Docs](https://code.visualstudio.com/docs/editor/userdefinedsnippets)
