### ISSUE TITLE
不会检测当前使用的profile，总是操作到 ‘default’ 的profile

### ISSUE THREAD

**Issue by Gerson-577** [inu1255/vscode-easy-snippet#48]
在 visual studio code 中，用户当前的配置默认是使用 “default”。

我自己自定义了一个 vue-typescript-front profile
 所有的一套的东西 转移到了另一个空间。
 
  snippet 不是 在User\snippets\typescript.json
 
 而可能是在 User\profiles\-7b5a4b43\snippets\typescript.json 中

**Comment by inu1255** [comment]
现在可以设置`Snippets Path`
![image](https://github.com/inu1255/vscode-easy-snippet/assets/5772409/f32edd13-898d-4971-89bd-0eab32fcd829)

**Comment by Gerson-577** [comment]
能不能直接获取当前正在使用的 profile 路径，我对你的插件改了下目前也是自己手动配 snippets path

**Comment by inu1255** [comment]
@Gerson-577 我没有找到这个获取的方法。如果您有好的建议可以提供一下
