### ISSUE TITLE
Change keybinding for easySnippet.run 

### ISSUE THREAD

**Issue by jabacchetta** [inu1255/vscode-easy-snippet#5]
The `easySnippet.run` keybinding chord starts with `cmd+.` This breaks VSCode's default quick fix shortcuts that are set to `cmd+.`

I'd recommend using the sequence `cmd+k` that VSCode often uses to start chords with. So maybe `cmd+k -> shift+command+s`

**Comment by jabacchetta** [comment]
Looks like this has been resolved as suggested.

**Comment by flaviofl** [comment]
Oh no! **shift+command+s** on Mac is a shortcut to **save as**   
<img width="340" alt="Screen Shot 2020-08-25 at 22 02 19" src="https://user-images.githubusercontent.com/6733285/91171914-afa3bc80-e71e-11ea-9071-bcba8e673281.png">

**Comment by McGeeP** [comment]
I am on a Mac and can't get the key shortcut to work?

cmd+k doesn't do anything. Am I missing something?

**Comment by melMass** [comment]
This is the shortcut for save without formatting too btw
