### ISSUE TITLE
Error: v.split is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by therealsujitk** [inu1255/vscode-easy-snippet#51]
While trying to open some of my existing snippets with this extension I get the following error.

```
v.split is not a function or its return value is not iterable
```

I was able to figure out the root cause of this issue, this happens when value for the prefix is an array of strings instead of a simple string. For example,

```json
{
    "Hello World": {
        "description": "Print hello world",
        "prefix": [
            "hello",
            "world"
        ],
    "body": [
        "print('Hello World!')"
    ]
}
```

To resolve this I propose allowing multiple lines with the `@prefix` annotation. For example,

```py
# @prefix hello
# @prefix world
# @description Print hello world

print('Hello World!')
```

**Comment by therealsujitk** [comment]
@inu1255 if you aren't planning to work on this, I can probably implement it. Can you assign me to this issue?

**Comment by inu1255** [comment]
@therealsujitk I've commited some fixes. If there is still some bug, I would be happy to accept your pull request.

**Comment by therealsujitk** [comment]
@inu1255 this seems to be fixed now.
