### ISSUE TITLE
Not working on other profile

### ISSUE THREAD

**Issue by black-coda** [inu1255/vscode-easy-snippet#52]
After creating a profile aside from the default, the snippets fail to work on them.

**Comment by wcervini** [comment]
have tthe same error, on default profile works fine, but if you change to an other profile the profi trigger doesn't work

**Comment by inu1255** [comment]
now you can set `Snippets Path` on other profile
![image](https://github.com/inu1255/vscode-easy-snippet/assets/5772409/3a3a8d3c-636e-45d4-ba01-da94a7e53872)

**Comment by wcervini** [comment]
Thanks a lot
